image:
  repository: local/ephemerator
  # Overrides the image tag whose default is the chart appVersion.
  pullPolicy: IfNotPresent
  tag: latest

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1000

operator:
  env:
    - name: 'EPHEMERATE_INTERVAL'
      value: '60'
    - name: 'EPHEMERATOR_IGNORE_NAMESPACES'
      value: 'namespace-ignored'
resources:
  requests:
    cpu: '50m'
    memory: '100Mi'
  limits:
    cpu: '100m'
    memory: '250Mi'
