apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: ephemerators.tessellate.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: tessellate.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                  - resourceToWatch
                  - lifetime
              x-kubernetes-preserve-unknown-fields: true
              properties:
                resourceToWatch:
                  type: object
                  properties:
                    namespace:
                      type: string
                lifetime:
                  type: object
                  oneOf:
                  - required: ["duration"]
                  - required: ["until"]
                  properties:
                    duration:
                      type: object
                      anyOf:
                        - required: ["minutes"]
                        - required: ["hours"]
                        - required: ["days"]
                        - required: ["weeks"]
                        - required: ["months"]
                        - required: ["years"]
                      properties:
                        minutes:
                          type: integer
                        hours:
                          type: integer
                        days:
                          type: integer
                        weeks:
                          type: integer
                        months:
                          type: integer
                        years:
                          type: integer
                    until:
                      type: object
                      required:
                        - date
                        - time
                        - timezone
                      properties:
                        date:
                          type: string
                        time:
                          type: string
                        timezone:
                          type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                expiresAtSeconds:
                  type: integer
                expiresAt:
                  type: string
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: ephemerators
    # singular name to be used as an alias on the CLI and for display
    singular: ephemerator
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Ephemerator
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - eph
