apiVersion: v1
kind: Namespace
metadata:
  name: namespace-ephemerator-test3
  labels:
    name: namespace-ephemerator-test3
---
apiVersion: tessellate.io/v1alpha1
kind: Ephemerator
metadata:
    name: ephemerator-disabled
    annotations:
        ephemerators.tessellate.io/enabled: 'false'
spec:
    resourceToWatch:
      namespace: namespace-ephemerator-test3
    lifetime:
      duration:
        hours: 1